version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /home/wando/portfolio-projects/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    networks:
      - proxy_net
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: encrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /home/wando/portfolio-projects/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      - proxy_net
  certs:
    image: tutum/apache-php
    container_name: certs
    environment:
      - VIRTUAL_HOST=m.hillarywando.com,www.m.hillarywando.com,flask-book-api.m.hillarywando.com,www.flask-book-api.m.hillarywando.com
      - LETSENCRYPT_HOST=m.hillarywando.com,www.m.hillarywando.com,flask-book-api.m.hillarywando.com,www.flask-book-api.m.hillarywando.com
      - LETSENCRYPT_EMAIL=hillarywando@gmail.com
    networks:
      - cert_net
  portfolio:
    image: wandonium/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    depends_on:
      - nginx-proxy
      - letsencrypt
    environment:
      - VIRTUAL_HOST=m.hillarywando.com,www.m.hillarywando.com
    networks:
      - proxy_net
networks:
  cert_net:
    driver: bridge
  proxy_net:
    driver: bridge